[profile.default]
src = "src"
out = "out"
libs = ["lib"]

solc_version = '0.8.27'
optimizer = true
optimizer_runs = 10000

gas_reports = [
  # "*",
]

[fmt]
line_length=130
tab_width=4
func_attrs_with_params_multiline=true