name: Slither Analysis

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# Add this permissions block
permissions:
  contents: read
  security-events: write
  issues: write

jobs:
  analyze-core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install dependencies
        run: forge install
        
      - name: Run Slither core
        uses: crytic/slither-action@v0.4.0
        continue-on-error: true
        id: slither
        with:
          slither-config: "slither.config.json"
          solc-version: 0.8.27
          sarif: results.sarif
          fail-on: none

      - name: Upload SARIF file for core
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.slither.outputs.sarif }}